### ISSUE TITLE
[Umbrella] 2000+ Applications support.

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#4225]
# Summary

The user interface becomes notably slower if one Argo CD instance manages more than 1 thousand applications. Multiple independent improvements are required to improve performance. This is an umbrella ticket to document finding of required improvements and track progress.

Issues/improvements found so far:

* [x] Application list page unnecessary loads all projects https://github.com/argoproj/argo-cd/issues/4224
* [x] Argo CD API server should support gzip compression https://github.com/argoproj/argo-cd/issues/4226
* [x] fix: improve applications list page client side performance https://github.com/argoproj/argo-cd/pull/4244
* [x] Progress indicators in Argo CD UI https://github.com/argoproj/argo-cd/issues/4227
* [x] Failed manifest generation protection https://github.com/argoproj/argo-cd/issues/4238

**Comment by alexmt** [comment]
Done
