### ISSUE TITLE
Repo browsing to improve app creation process

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#71]
The current way of enabling applications via the CLI can be error prone. It would be nice to have the ability to create apps via the UI by browsing the git repo for the ksonnet app. This requires the repo server to provide listdir functionality, possibly using the GitHub APIs or by checking out the repository and doing filesystem syscalls.

UI design: https://projects.invisionapp.com/share/J8IUZD96ZCP#/screens/291683071

UI tickets:

- [ ] Redesign application list page (https://github.com/argoproj/argo-cd/issues/243)
- [ ] Repositories list page (https://github.com/argoproj/argo-cd/issues/241)
- [ ] Application creation wizard (https://github.com/argoproj/argo-cd/issues/242)

**Comment by alexmt** [comment]
Simple application form had been implemented. Moving ticket to 0.4.0 to track repo browsing feature implementation

**Comment by merenbach** [comment]
@jessesuen @mukulikak some more information on this would be super helpful.  Is this ticket to add a new way to create apps, or simply to add repo browsing?  Is this a matter of just storing a list of the files in a repo?  Don't we already keep a local cache of the entire repo contents?

**Comment by alexmt** [comment]
@merenbach I've attached UI mockup link: https://projects.invisionapp.com/share/J8IUZD96ZCP#/screens/291683071

**Comment by merenbach** [comment]
Started a branch `repo-browsing`.

**Comment by merenbach** [comment]
I believe that backend is done at this time.  @alexmt please feel free to let me know if I may assist with frontend or if additional backend changes come up.

**Comment by alexmt** [comment]
UI changes are done.
